export default function TermsOfUse() {
  return (
    <main
      style={{
        maxWidth: 720,
        margin: "0 auto",
        padding: "3rem 1.5rem",
        fontFamily: "Segoe UI, sans-serif",
        color: "#e2e8f0",
        background: "#0f172a",
        minHeight: "100vh",
        lineHeight: 1.7,
      }}
    >
      <h1 style={{ fontSize: "2rem", fontWeight: 700, color: "#06B6D4", marginBottom: "0.5rem" }}>
        Terms of Use
      </h1>
      <p style={{ color: "#64748b", marginBottom: "2rem" }}>
        Last updated: March 2026 · SignBridge AI · Microsoft Innovation Challenge 2026
      </p>

      <Section title="1. About SignBridge AI">
        SignBridge AI is an inclusive communication platform developed for the
        <strong> Microsoft Innovation Challenge 2026</strong> hackathon. It provides real-time
        speech-to-sign language (ASL) translation using Microsoft Azure AI services, supporting
        deaf and hard-of-hearing individuals in meetings and conversations.
      </Section>

      <Section title="2. Acceptable Use">
        By using SignBridge AI you agree to:
        <ul>
          <li>Use the app for legitimate communication and accessibility purposes</li>
          <li>Not submit content that is harmful, offensive, or violates Microsoft&apos;s content policies</li>
          <li>Not attempt to circumvent the Responsible AI safeguards built into the platform</li>
          <li>Not use the platform for automated or bulk processing without authorization</li>
        </ul>
      </Section>

      <Section title="3. Educational & Hackathon Context">
        This application was built as a proof-of-concept for the Microsoft Innovation Challenge
        2026. The sign language translations provided are intended to be assistive and
        educational. SignBridge AI should not be used as the sole communication aid in
        safety-critical or legal contexts without human interpreter verification.
      </Section>

      <Section title="4. AI-Generated Content Disclaimer">
        Sign language sequences are generated by Azure OpenAI (GPT-4o) and may not perfectly
        represent ASL grammar in all cases. The app uses a curated set of 62+ known ASL signs
        and fingerspelling for unknown words. Users should verify critical communications with
        a qualified ASL interpreter.
      </Section>

      <Section title="5. Responsible AI">
        SignBridge AI implements Microsoft&apos;s Responsible AI principles:
        <ul>
          <li><strong>Fairness</strong> — equal support for English, Spanish, and Portuguese speakers</li>
          <li><strong>Reliability</strong> — fail-open design with local fallbacks when AI services are unavailable</li>
          <li><strong>Privacy &amp; Security</strong> — PII detection and redaction before AI processing</li>
          <li><strong>Inclusiveness</strong> — built specifically to empower deaf and hard-of-hearing users</li>
          <li><strong>Transparency</strong> — full AI decision log available in the Responsible AI panel</li>
        </ul>
      </Section>

      <Section title="6. Service Availability">
        This is a hackathon demonstration. Service availability is not guaranteed beyond the
        competition period. Azure resource costs are covered by the development team&apos;s
        Azure subscription for the duration of the challenge.
      </Section>

      <Section title="7. Intellectual Property">
        The SignBridge AI codebase, 3D avatar system, and sign animation library were developed
        by the SignBridge AI team. Azure AI services are the intellectual property of Microsoft.
        The MediaPipe hand tracking library is provided by Google under Apache 2.0.
      </Section>

      <Section title="8. Limitation of Liability">
        SignBridge AI is provided &quot;as is&quot; for hackathon evaluation purposes. The development
        team is not liable for any direct or indirect damages arising from use of the platform.
      </Section>

      <Section title="9. Contact">
        Built for the Microsoft Innovation Challenge 2026. For questions, use the feedback
        channel provided by the event organizers.
      </Section>
    </main>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section style={{ marginBottom: "2rem" }}>
      <h2 style={{ fontSize: "1.2rem", fontWeight: 600, color: "#cbd5e1", marginBottom: "0.75rem" }}>
        {title}
      </h2>
      <div style={{ color: "#94a3b8" }}>{children}</div>
    </section>
  );
}
