#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# SignBridge AI — Azure Bicep Deployment Script
# Usage: ./deploy.sh [dev|prod] [resource-group] [subscription-id]
# ─────────────────────────────────────────────────────────────────────────────

set -euo pipefail

ENV="${1:-dev}"
RG="${2:-signbridge-rg-${ENV}}"
SUBSCRIPTION="${3:-$(az account show --query id -o tsv)}"
LOCATION="eastus2"

echo "🚀 Deploying SignBridge AI to environment: ${ENV}"
echo "   Resource Group : ${RG}"
echo "   Subscription   : ${SUBSCRIPTION}"
echo "   Location       : ${LOCATION}"
echo ""

# Ensure logged in
az account set --subscription "${SUBSCRIPTION}"

# Create resource group if it doesn't exist
az group create \
  --name "${RG}" \
  --location "${LOCATION}" \
  --tags \
    project=signbridge-ai \
    challenge=inclusive-communication-hub \
    hackathon=microsoft-innovation-march-2026 \
    env="${ENV}"

echo "✅ Resource group ready: ${RG}"

# Validate before deploying
echo "🔍 Validating Bicep template..."
az deployment group validate \
  --resource-group "${RG}" \
  --template-file "$(dirname "$0")/main.bicep" \
  --parameters "$(dirname "$0")/parameters.${ENV}.json"

echo "✅ Validation passed"

# Deploy
echo "📦 Deploying resources (this takes ~10-15 minutes)..."
DEPLOYMENT_OUTPUT=$(az deployment group create \
  --resource-group "${RG}" \
  --template-file "$(dirname "$0")/main.bicep" \
  --parameters "$(dirname "$0")/parameters.${ENV}.json" \
  --name "signbridge-${ENV}-$(date +%Y%m%d%H%M%S)" \
  --output json)

echo ""
echo "✅ Deployment complete!"
echo ""
echo "─── Outputs ──────────────────────────────────────────────────────────────"
echo "${DEPLOYMENT_OUTPUT}" | jq -r '.properties.outputs | to_entries[] | "  \(.key): \(.value.value)"'
echo ""

# Write outputs to .env.local for local development
if [ "${ENV}" = "dev" ]; then
  OUTPUT_FILE="../.env.local"
  echo "# Auto-generated by deploy.sh on $(date)" > "${OUTPUT_FILE}"

  APP_URL=$(echo "${DEPLOYMENT_OUTPUT}" | jq -r '.properties.outputs.appServiceUrl.value')
  FUNC_URL=$(echo "${DEPLOYMENT_OUTPUT}" | jq -r '.properties.outputs.functionAppUrl.value')
  OPENAI_ENDPOINT=$(echo "${DEPLOYMENT_OUTPUT}" | jq -r '.properties.outputs.openAiEndpoint.value')
  SIGNALR_URL=$(echo "${DEPLOYMENT_OUTPUT}" | jq -r '.properties.outputs.signalRUrl.value')
  COSMOS_ENDPOINT=$(echo "${DEPLOYMENT_OUTPUT}" | jq -r '.properties.outputs.cosmosEndpoint.value')
  KV_URI=$(echo "${DEPLOYMENT_OUTPUT}" | jq -r '.properties.outputs.keyVaultUri.value')

  cat >> "${OUTPUT_FILE}" << EOF
AZURE_OPENAI_ENDPOINT=${OPENAI_ENDPOINT}
AZURE_OPENAI_KEY=<fetch-from-key-vault>
AZURE_OPENAI_DEPLOYMENT=gpt-4o
AZURE_SPEECH_KEY=<fetch-from-key-vault>
AZURE_SPEECH_REGION=eastus2
AZURE_CONTENT_SAFETY_ENDPOINT=<see-outputs>
AZURE_CONTENT_SAFETY_KEY=<fetch-from-key-vault>
AZURE_SIGNALR_CONNECTION_STRING=<fetch-from-key-vault>
AZURE_COSMOS_ENDPOINT=${COSMOS_ENDPOINT}
AZURE_COSMOS_KEY=<fetch-from-key-vault>
AZURE_COSMOS_DATABASE=signbridge
AZURE_STORAGE_CONNECTION_STRING=<fetch-from-key-vault>
AZURE_STORAGE_CONTAINER=signbridge-assets
AZURE_KEY_VAULT_URI=${KV_URI}
NEXT_PUBLIC_SIGNALR_URL=${SIGNALR_URL}
EOF

  echo "📝 .env.local written to ${OUTPUT_FILE}"
  echo "   Note: replace <fetch-from-key-vault> values using:"
  echo "   az keyvault secret show --vault-name signbridge-kv-dev --name <secret-name> --query value -o tsv"
fi

echo ""
echo "🎉 SignBridge AI infrastructure ready!"
