#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# SignBridge AI — Azure Bicep Deployment Script
# Usage: ./deploy.sh [dev|prod] [resource-group] [subscription-id]
# ─────────────────────────────────────────────────────────────────────────────

set -euo pipefail

ENV="${1:-dev}"
RG="${2:-signbridge-rg-${ENV}}"
SUBSCRIPTION="${3:-$(az account show --query id -o tsv)}"
LOCATION="${4:-eastus2}"
STRICT_QUOTA_CHECK="${STRICT_QUOTA_CHECK:-false}"
DEPLOYMENT_JSON_FILE="$(dirname "$0")/.last-deployment-${ENV}.json"
MAX_RETRIES="${MAX_RETRIES:-3}"
RETRY_BASE_DELAY_SEC="${RETRY_BASE_DELAY_SEC:-5}"

is_transient_error() {
  local output="$1"
  echo "${output}" | grep -Eqi 'TooManyRequests|throttl|timed out|timeout|temporar|temporarily unavailable|InternalServerError|GatewayTimeout|ServiceUnavailable|operation could not be completed'
}

retry_cmd() {
  local attempt=1
  local delay="${RETRY_BASE_DELAY_SEC}"
  local output

  while true; do
    if output=$("$@" 2>&1); then
      if [ -n "${output}" ]; then
        echo "${output}"
      fi
      return 0
    fi

    if [ "${attempt}" -ge "${MAX_RETRIES}" ]; then
      echo "${output}" >&2
      return 1
    fi

    if is_transient_error "${output}"; then
      echo "⚠️  Transient error on attempt ${attempt}/${MAX_RETRIES}; retrying in ${delay}s..." >&2
      echo "   ${output}" >&2
      sleep "${delay}"
      attempt=$((attempt + 1))
      delay=$((delay * 2))
      continue
    fi

    echo "${output}" >&2
    return 1
  done
}

check_quota_scope() {
  local scope="$1"
  local label="$2"
  local reachable=true

  if az quota list --scope "${scope}" --output none > /dev/null 2>&1; then
    echo "✅ ${label} quota scope is reachable"
  else
    reachable=false
    echo "⚠️  ${label} quota scope could not be validated or has insufficient access/quota"
    echo "   Continuing to next step (non-blocking quota validation)."
  fi

  if [ "${reachable}" = false ] && [ "${STRICT_QUOTA_CHECK}" = "true" ]; then
    echo "✗ STRICT_QUOTA_CHECK=true and quota validation failed for ${label}. Aborting." >&2
    exit 1
  fi
}

echo "🚀 Deploying SignBridge AI to environment: ${ENV}"
echo "   Resource Group : ${RG}"
echo "   Subscription   : ${SUBSCRIPTION}"
echo "   Location       : ${LOCATION}"
echo "   Strict Quota   : ${STRICT_QUOTA_CHECK}"
echo ""

# Ensure logged in
az account set --subscription "${SUBSCRIPTION}"

# Best-effort quota validation (non-blocking)
echo "🔎 Validating quota requirements (non-blocking)..."
check_quota_scope "/subscriptions/${SUBSCRIPTION}/providers/Microsoft.CognitiveServices/locations/${LOCATION}" "Cognitive Services (${LOCATION})"
check_quota_scope "/subscriptions/${SUBSCRIPTION}/providers/Microsoft.Web/locations/${LOCATION}" "App Service (${LOCATION})"
check_quota_scope "/subscriptions/${SUBSCRIPTION}/providers/Microsoft.SignalRService/locations/${LOCATION}" "SignalR (${LOCATION})"
echo "✅ Quota validation step finished"
echo ""

# Create resource group if it doesn't exist
retry_cmd az group create \
  --name "${RG}" \
  --location "${LOCATION}" \
  --tags \
    project=signbridge-ai \
    challenge=inclusive-communication-hub \
    hackathon=microsoft-innovation-march-2026 \
    env="${ENV}"

echo "✅ Resource group ready: ${RG}"

# Validate before deploying
echo "🔍 Validating Bicep template..."
retry_cmd az deployment group validate \
  --resource-group "${RG}" \
  --template-file "$(dirname "$0")/main.bicep" \
  --parameters "$(dirname "$0")/parameters.${ENV}.json"

echo "✅ Validation passed"

# Deploy
echo "📦 Deploying resources (this takes ~10-15 minutes)..."
DEPLOYMENT_OUTPUT=$(retry_cmd az deployment group create \
  --resource-group "${RG}" \
  --template-file "$(dirname "$0")/main.bicep" \
  --parameters "$(dirname "$0")/parameters.${ENV}.json" \
  --name "signbridge-${ENV}-$(date +%Y%m%d%H%M%S)" \
  --output json)

echo "${DEPLOYMENT_OUTPUT}" > "${DEPLOYMENT_JSON_FILE}"

echo ""
echo "✅ Deployment complete!"
echo ""
echo "─── Outputs ──────────────────────────────────────────────────────────────"
echo "${DEPLOYMENT_OUTPUT}" | jq -r '.properties.outputs | to_entries[] | "  \(.key): \(.value.value)"'
echo "  deploymentOutputFile: ${DEPLOYMENT_JSON_FILE}"
echo ""

APP_URL=$(echo "${DEPLOYMENT_OUTPUT}" | jq -r '.properties.outputs.appServiceUrl.value')
FUNC_URL=$(echo "${DEPLOYMENT_OUTPUT}" | jq -r '.properties.outputs.functionAppUrl.value')

echo "🔬 Running infrastructure smoke checks..."
retry_cmd az webapp show --resource-group "${RG}" --name "$(echo "${APP_URL}" | sed -E 's#https://([^.]*)\..*#\1#')" --query "state" --output tsv > /dev/null
retry_cmd az functionapp show --resource-group "${RG}" --name "$(echo "${FUNC_URL}" | sed -E 's#https://([^.]*)\..*#\1#')" --query "state" --output tsv > /dev/null
echo "✅ Infrastructure smoke checks passed"
echo ""

# Write outputs to .env.local for local development
if [ "${ENV}" = "dev" ]; then
  OUTPUT_FILE="../.env.local"
  echo "# Auto-generated by deploy.sh on $(date)" > "${OUTPUT_FILE}"

  OPENAI_ENDPOINT=$(echo "${DEPLOYMENT_OUTPUT}" | jq -r '.properties.outputs.openAiEndpoint.value')
  SIGNALR_URL=$(echo "${DEPLOYMENT_OUTPUT}" | jq -r '.properties.outputs.signalRUrl.value')
  COSMOS_ENDPOINT=$(echo "${DEPLOYMENT_OUTPUT}" | jq -r '.properties.outputs.cosmosEndpoint.value')
  KV_URI=$(echo "${DEPLOYMENT_OUTPUT}" | jq -r '.properties.outputs.keyVaultUri.value')
  KV_NAME=$(echo "${KV_URI}" | sed -E 's#https://([^.]*)\..*#\1#')

  cat >> "${OUTPUT_FILE}" << EOF
AZURE_OPENAI_ENDPOINT=${OPENAI_ENDPOINT}
AZURE_OPENAI_KEY=<fetch-from-key-vault>
AZURE_OPENAI_DEPLOYMENT=gpt-4o
AZURE_SPEECH_KEY=<fetch-from-key-vault>
AZURE_SPEECH_REGION=eastus2
AZURE_CONTENT_SAFETY_ENDPOINT=<see-outputs>
AZURE_CONTENT_SAFETY_KEY=<fetch-from-key-vault>
AZURE_SIGNALR_CONNECTION_STRING=<fetch-from-key-vault>
AZURE_COSMOS_ENDPOINT=${COSMOS_ENDPOINT}
AZURE_COSMOS_KEY=<fetch-from-key-vault>
AZURE_COSMOS_DATABASE=signbridge
AZURE_STORAGE_CONNECTION_STRING=<fetch-from-key-vault>
AZURE_STORAGE_CONTAINER=signbridge-assets
AZURE_KEY_VAULT_URI=${KV_URI}
NEXT_PUBLIC_SIGNALR_URL=${SIGNALR_URL}
EOF

  echo "📝 .env.local written to ${OUTPUT_FILE}"
  echo "   Note: replace <fetch-from-key-vault> values using:"
  echo "   az keyvault secret show --vault-name ${KV_NAME} --name <secret-name> --query value -o tsv"
fi

echo ""
echo "🎉 SignBridge AI infrastructure ready!"
